language: php

php:
  - 7.1

matrix:
  include:
    - php: 7.1
    - env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - composer self-update
  - composer update ${COMPOSER_FLAGS}

script:
  - ./vendor/bin/phpunit
